# Generated by Django 4.1.7 on 2023-03-07 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ServicesADomicile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionnelService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux_horaire', models.FloatField()),
                ('service_id', models.PositiveSmallIntegerField()),
                ('user_id', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Soumission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_planification', models.DateField(default=django.utils.timezone.now)),
                ('date_terminee', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('user_id', models.PositiveSmallIntegerField()),
                ('professionnel_service_id', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
