# Generated by Django 4.1.7 on 2023-03-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServicesADomicile', '0002_professionnelservice_service_soumission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soumission',
            name='etat',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'En_attente'), (2, 'Acceptee'), (3, 'Terminee'), (4, 'Annulee')], null=True),
        ),
    ]
