# Generated by Django 4.1.7 on 2023-03-07 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServicesADomicile', '0003_soumission_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionnelservice',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServicesADomicile.service'),
        ),
        migrations.AlterField(
            model_name='professionnelservice',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='soumission',
            name='professionnel_service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServicesADomicile.professionnelservice'),
        ),
        migrations.AlterField(
            model_name='soumission',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
